//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMvcKutuphaneEntities : DbContext
    {
        public DbMvcKutuphaneEntities()
            : base("name=DbMvcKutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblcezalar> tblcezalar { get; set; }
        public virtual DbSet<tblhareket> tblhareket { get; set; }
        public virtual DbSet<tblkasa> tblkasa { get; set; }
        public virtual DbSet<tblkategori> tblkategori { get; set; }
        public virtual DbSet<tblkitap> tblkitap { get; set; }
        public virtual DbSet<tblpersonel> tblpersonel { get; set; }
        public virtual DbSet<tbluyeler> tbluyeler { get; set; }
        public virtual DbSet<tblyazar> tblyazar { get; set; }
        public virtual DbSet<tblhakkimizda> tblhakkimizda { get; set; }
        public virtual DbSet<tbliletisim> tbliletisim { get; set; }
        public virtual DbSet<tblmesajlar> tblmesajlar { get; set; }
    }
}
