//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhareket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblhareket()
        {
            this.tblcezalar = new HashSet<tblcezalar>();
        }
    
        public int id { get; set; }
        public Nullable<int> kitap { get; set; }
        public Nullable<int> uye { get; set; }
        public Nullable<int> personel { get; set; }
        public Nullable<System.DateTime> alistarihi { get; set; }
        public Nullable<System.DateTime> iadetarihi { get; set; }
        public Nullable<bool> islemdurum { get; set; }
        public Nullable<System.DateTime> uyegetirtarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcezalar> tblcezalar { get; set; }
        public virtual tblkitap tblkitap { get; set; }
        public virtual tbluyeler tbluyeler { get; set; }
        public virtual tblpersonel tblpersonel { get; set; }
    }
}
